name: "HawkScan SARIF Tester"

on:
  push:

jobs:
  test-job:
    name: "HawkScan SARIF Tester"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@feature/sarif-option
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          codeScanningAlerts: true
          githubToken: ${{ github.token }}
          
